name: Node.js Package

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: 'https://registry.npmjs.org/hs-sample-package'
      - run: npm install --prefix ./sample-packages/npm/ --folder ./sample-packages/npm/
      - run: npm ci --prefix ./sample-packages/npm/ --folder ./sample-packages/npm/
      - run: npm publish --prefix ./sample-packages/npm/ --folder ./sample-packages/npm/
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
